export const displayStyle = (() => {
    return {
        inline : { display: 'inline' },
        block : { display: 'block' },
        contents : { display: 'contents' },
        flex : { display: 'flex' },
        grid : { display: 'grid' },
        inlineBlock : { display: 'inline-block' },
        inlineFlex : { display: 'inline-flex' },
        inlineGrid : { display: 'inline-grid' },
        inlineTable : { display: 'inline-table' },
        listItem : { display: 'list-item' },
        runIn : { display: 'run-in' },
        table : { display: 'table' },
        tableCaption : { display: 'table-caption' },
        tableColumnGroup : { display: 'table-column-group' },
        tableHeaderGroup : { display: 'table-header-group' },
        tableFooterGroup : { display: 'table-footer-group' },
        tableRowGroup : { display: 'table-row-group' },
        tableCell : { display: 'table-cell' },
        tableColumn : { display: 'table-column' },
        tableRow : { display: 'table-row' },
        none : { display: 'none' },
        initial : { display: 'initial' },
        inherit : { display: 'inherit' },
    }
})();
